### ISSUE TITLE
Payment proof

### ISSUE THREAD

**Issue by Endrju00** [justdodo27/financepal#30]
* Dodać pole "name" do POST /payment_proofs/ w API.
* Fajnie by było jakby odpowiedź po utworzeniu miała faktycznie url prowadzący do pliku bo na razie jest ścieżka do lokalnego pliku na urządzeniu a nie poprzez serwer (w GET wszystko jest git)
```json
{
    "filename": "endrju-3ef2a2e5-9fed-4858-bae1-8a60799350c0-purple-sunrise.jpg",
    "url": "/app/backend/static/endrju-3ef2a2e5-9fed-4858-bae1-8a60799350c0-purple-sunrise.jpg",
    "user_id": 1,
    "id": 4,
    "payments": []
}
```

**Comment by justdodo27** [comment]
![image](https://github.com/justdodo27/financepal/assets/18745077/f2307597-9ec5-45a7-a712-570fd551e3aa)
